# Examen Parcial n°1 2da Parte - TLP3 - Python para Ciencia de Datos.

**A partir del datasets brindado, realizar los siguientes procedimientos:**

* Importar datasets con Pandas.
* Explorar los datos con los metodos correspondientes. 
* Limpieza de los datos (Normalización de datos).
* Obtener estadisticas.
* Mostrar los datos procesados con graficos utilizando la libreria Matplotlib.
* Exportar el contenido a un archivo sqlite utilizando PANDAS.


**Importante: Se debe documentar cada procedimiento realizado, siguiendo la siguiente estructura:**

1. Celda de Markdown (Documentación)
2. Código (Sin comentarios, se debe documentar lo sufiente solo en la celda de markdown).


### Criterios de Evaluación:

1. No esta permitido el uso de IAs durante el examen. (Desactivar Copilot o cualquier herramienta de IA para autocompletar codigo.)

2. Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).

3. Comentarios claros y concisos que expliquen el propósito de cada sección del código en una celda de markdown antes del código.

4. Utilizar mensajes de commit descriptivos. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE).

5. Entrega en tiempo y forma (Parciales entregados fuera de hora o con commits pasados el horario de entrega quedará invalidado.)

6. Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: 
**parcial1_tlp3_nombre_apellido**).

7. Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter.

8. Deben trabajar con el datasets adjunto.

9. Una vez finalizado el examen, los resultados deben quedar guardados debajo de cada celda (NO EJECUTAR LA OPCIÓN "borrar todas las salidas").

**Importante:** Una vez finalizado el examen, marcar como completado en el classroom.

## Actividades: 
### 1. Importación del Dataset con Pandas

En esta sección, se debe utilizar la librería Pandas para cargar el archivo CSV que contiene los datos de CALIFICACIONES en un DataFrame.

### 2. Exploración Inicial de los Datos

A continuación, se deben emplear métodos de Pandas para obtener una visión general del dataset. 
- 2.1: Visualizar las primeras filas y ultimas.
- 2.2: Obtener informacion del df con su metodo correspondiente.
- 2.3: Hacer un conteo de valores nulos.

### 3. Limpieza y Normalización de los Datos

- 3.1. Esta etapa crucial deben aplicar la corrección de diversos errores presentes en el dataset. Se abordarán los valores faltantes (Deben aplicar los metodos que ustedes crean convenientes **(Solo 1)**, por ejemplo: Eliminación de filas, cubrir valores con media, mediana, etc.)
- 3.2: La columna Fecha deberan pasarla al tipo datetime con su metodo correspondiente.
- 3.3: Corregir las mayusculas en el caso de Nombre y Apellido (Si es que corresponde.)


### 4. Obtención de Estadísticas Descriptivas

Después de la limpieza, deben hacer lo siguiente: 

- 4.1: calcular nuevamente las estadísticas descriptivas para observar el impacto del proceso de limpieza en los datos numéricos.
- 4.2: Calcular estadísticas específicas por grupo (Agrupar dos columnas).

### 5. Visualización de los Datos con Matplotlib

En esta sección, deben utilizar la librería Matplotlib para crear **UNA** visualización que permitan comprender mejor los datos de ventas.El grafico es a elección, puede crear **UNO** de los siguientes: histogramas, diagramas de dispersión, gráficos de barras y graficos de torta.

### 6. Exportación a Archivo SQLite

Finalmente, deben utilizar la funcionalidad de Pandas para guardar el DataFrame procesado en una base de datos SQLite. Deben hacer una conexión y hacer una consulta para ver si los datos fueron cargados correctamente.

### 1. Importación del Dataset con Pandas
- A continuación, se importará el dataset proporcionado utilizando Pandas

In [7]:
import pandas as pd

df = pd.read_csv('calificaciones.csv')

### 2. Exploración Inicial de los Datos
- Empezamos a visualizar los datos del dataframe para saber con que datos vamos a trabajar

In [8]:
print(df.head())
print(70*'*')
print(df.tail())
print(70*'*')
print(df.info())
print(70*'*')
print(df.isnull().sum())

     nombre   apellido  parcial1  parcial2  nota_final       fecha  aprobado
0  federico     torres       NaN       6.9         6.1  2024-03-23        sí
1  federico    ramirez       8.7       6.6         NaN  2024-04-04  Aprobado
2  federico  fernandez       NaN       NaN         7.1  2024-10-27        NO
3     maría     torres       5.5       8.8         2.0  2024-06-14        NO
4  agustina  fernandez       6.8       7.3         4.0  2024-08-21        Si
**********************************************************************
       nombre   apellido  parcial1  parcial2  nota_final       fecha  \
96     martín      gomez       4.1       8.7         NaN  2024-07-02
97     andrés      gomez       1.2       NaN         3.9  2024-11-04
98   federico  rodriguez       9.1       8.6         NaN  2024-05-11
99   federico    pereyra       NaN       1.7         2.2  2024-05-20
100  federico       ruiz       3.5       7.1         8.6  2024-03-07

      aprobado
96          sí
97    aprobado
98          Si
99   Reprobado
100         sí
**********************************************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nombre      101 non-null    object
 1   apellido    101 non-null    object
 2   parcial1    82 non-null     float64
 3   parcial2    68 non-null     float64
 4   nota_final  63 non-null     float64
 5   fecha       101 non-null    object
 6   aprobado    101 non-null    object
dtypes: float64(3), object(4)
memory usage: 5.7+ KB
None
**********************************************************************
nombre         0
apellido       0
parcial1      19
parcial2      33
nota_final    38
fecha          0
aprobado       0
dtype: int64

### 3. Limpieza y Normalización de los Datos
- En esta parte del trabajo se realizaría la normalización y la corrección de los datos

In [9]:
df.head()

     nombre   apellido  parcial1  parcial2  nota_final       fecha  aprobado
0  federico     torres       NaN       6.9         6.1  2024-03-23        sí
1  federico    ramirez       8.7       6.6         NaN  2024-04-04  Aprobado
2  federico  fernandez       NaN       NaN         7.1  2024-10-27        NO
3     maría     torres       5.5       8.8         2.0  2024-06-14        NO
4  agustina  fernandez       6.8       7.3         4.0  2024-08-21        Si

In [ ]:
df.dropna(subset=['parcial1','parcial2','nota_final'], inplace=True)

df['fecha'] = pd.to_datetime(df['fecha'], errors='coerce') 
df['nombre'] = df['nombre'].str.capitalize()
df['apellido'] = df['apellido'].str.capitalize()

df.head()

     nombre   apellido  parcial1  parcial2  nota_final      fecha   aprobado
3     María     Torres       5.5       8.8         2.0 2024-06-14         NO
4  Agustina  Fernandez       6.8       7.3         4.0 2024-08-21         Si
5    Camila   Martinez       9.3       3.6         9.1 2024-11-04         Si
6    Martín    Pereyra       5.0       2.7         6.1 2024-08-07   aprobado
7      Juan      Gomez       2.8       6.4         7.7 2024-07-06  reprobado

### 4. Obtención de Estadísticas Descriptivas

- Se calculan estadísticas generales y ademas por grupos para así poder tener una mejor comprensión sobre los datos con los que estamos trabajando ahora

In [ ]:
print(df.describe())
print(70*'*')
print(df.groupby('aprobado').describe())

        parcial1   parcial2  nota_final                fecha
count  36.000000  36.000000   36.000000                   36
mean    5.291667   5.463889    6.280556  2024-07-25 18:00:00
min     1.100000   1.100000    2.000000  2024-03-06 00:00:00
25%     3.675000   3.475000    4.850000  2024-06-04 18:00:00
50%     5.150000   5.650000    6.350000  2024-08-11 12:00:00
75%     7.225000   7.600000    7.700000  2024-09-19 18:00:00
max     9.600000   9.600000    9.900000  2024-12-14 00:00:00
std     2.514913   2.521468    2.045877                  NaN
**********************************************************************
          parcial1                                                   parcial2  \
             count      mean  min    25%   50%    75%  max       std    count
aprobado
Aprobado       3.0  5.833333  3.8  4.500  5.20  6.850  8.5  2.413158      3.0
NO             6.0  4.566667  1.2  3.575  4.90  5.475  7.6  2.178685      6.0
Reprobado      3.0  3.200000  1.7  2.700  3.70  3.950  4.2  1.322876      3.0
Si             6.0  6.116667  1.3  5.150  6.05  8.375  9.3  2.941032      6.0
aprobado       4.0  5.250000  1.1  4.025  5.15  6.375  9.6  3.474191      4.0
no             5.0  5.560000  3.6  3.700  4.80  7.100  8.6  2.207487      5.0
reprobado      4.0  5.650000  2.8  4.150  5.35  6.850  9.1  2.666458      4.0
sí             5.0  5.580000  1.7  3.500  5.20  8.600  8.9  3.149127      5.0

                     ... nota_final           fecha                       \
               mean  ...        max       std count                 mean
aprobado             ...
Aprobado   3.300000  ...        8.7  1.331666     3  2024-09-18 16:00:00
NO         4.583333  ...        7.0  1.875544     6  2024-06-25 00:00:00
Reprobado  6.233333  ...        7.7  1.514376     3  2024-10-02 08:00:00
Si         7.116667  ...        9.1  1.722788     6  2024-09-09 12:00:00
aprobado   5.400000  ...        8.7  2.244066     4  2024-07-22 00:00:00
no         4.820000  ...        8.8  1.837662     5  2024-07-05 14:24:00
reprobado  5.000000  ...        9.8  3.265348     4  2024-08-04 06:00:00
sí         6.440000  ...        9.9  2.434543     5  2024-05-10 04:48:00

                                                                          \
                           min                  25%                  50%
aprobado
Aprobado   2024-08-27 00:00:00  2024-09-09 00:00:00  2024-09-22 00:00:00
NO         2024-03-06 00:00:00  2024-06-08 18:00:00  2024-06-18 12:00:00
Reprobado  2024-09-19 00:00:00  2024-09-22 12:00:00  2024-09-26 00:00:00
Si         2024-05-09 00:00:00  2024-08-17 06:00:00  2024-09-08 00:00:00
aprobado   2024-06-06 00:00:00  2024-07-05 06:00:00  2024-07-26 12:00:00
no         2024-03-28 00:00:00  2024-06-01 00:00:00  2024-07-26 00:00:00
reprobado  2024-05-23 00:00:00  2024-06-25 00:00:00  2024-08-06 00:00:00
sí         2024-03-07 00:00:00  2024-04-03 00:00:00  2024-05-08 00:00:00


                           75%                  max  std
aprobado
Aprobado   2024-09-30 00:00:00  2024-10-08 00:00:00  NaN
NO         2024-06-23 18:00:00  2024-11-15 00:00:00  NaN
Reprobado  2024-10-09 00:00:00  2024-10-22 00:00:00  NaN
Si         2024-10-25 06:00:00  2024-12-14 00:00:00  NaN
aprobado   2024-08-12 06:00:00  2024-08-28 00:00:00  NaN
no         2024-08-27 00:00:00  2024-09-05 00:00:00  NaN
reprobado  2024-09-15 06:00:00  2024-10-13 00:00:00  NaN
sí         2024-05-10 00:00:00  2024-08-22 00:00:00  NaN

[8 rows x 32 columns]

### 5. Visualización de los Datos con Matplotlib

- En este punto se realizará un gráfico de barras 

En esta sección, deben utilizar la librería Matplotlib para crear **UNA** visualización que permitan comprender mejor los datos de ventas.El grafico es a elección, puede crear **UNO** de los siguientes: histogramas, diagramas de dispersión, gráficos de barras y graficos de torta.